/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "demuxL2.v:1" *)
module demuxL2(bclk, cclk, valid, data_in, valid_out0, valid_out1, data_out0, data_out1);
  (* src = "demuxL2.v:20" *)
  wire [7:0] _00_;
  (* src = "demuxL2.v:20" *)
  wire [7:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "demuxL2.v:2" *)
  input bclk;
  (* src = "demuxL2.v:3" *)
  input cclk;
  (* src = "demuxL2.v:12" *)
  wire [7:0] data_ant;
  (* src = "demuxL2.v:5" *)
  input [7:0] data_in;
  (* src = "demuxL2.v:8" *)
  output [7:0] data_out0;
  (* src = "demuxL2.v:9" *)
  output [7:0] data_out1;
  (* src = "demuxL2.v:4" *)
  input valid;
  (* src = "demuxL2.v:13" *)
  wire valid_ant;
  (* src = "demuxL2.v:6" *)
  output valid_out0;
  (* src = "demuxL2.v:7" *)
  output valid_out1;
  NOT _20_ (
    .A(data_ant[1]),
    .Y(_02_)
  );
  NOT _21_ (
    .A(valid_ant),
    .Y(_03_)
  );
  NOR _22_ (
    .A(_03_),
    .B(_02_),
    .Y(_00_[1])
  );
  NOT _23_ (
    .A(data_ant[2]),
    .Y(_04_)
  );
  NOR _24_ (
    .A(_04_),
    .B(_03_),
    .Y(_00_[2])
  );
  NOT _25_ (
    .A(data_ant[3]),
    .Y(_05_)
  );
  NOR _26_ (
    .A(_05_),
    .B(_03_),
    .Y(_00_[3])
  );
  NOT _27_ (
    .A(data_ant[4]),
    .Y(_06_)
  );
  NOR _28_ (
    .A(_06_),
    .B(_03_),
    .Y(_00_[4])
  );
  NOT _29_ (
    .A(data_ant[5]),
    .Y(_07_)
  );
  NOR _30_ (
    .A(_07_),
    .B(_03_),
    .Y(_00_[5])
  );
  NOT _31_ (
    .A(data_ant[6]),
    .Y(_08_)
  );
  NOR _32_ (
    .A(_08_),
    .B(_03_),
    .Y(_00_[6])
  );
  NOT _33_ (
    .A(data_ant[7]),
    .Y(_09_)
  );
  NOR _34_ (
    .A(_09_),
    .B(_03_),
    .Y(_00_[7])
  );
  NOT _35_ (
    .A(data_in[0]),
    .Y(_10_)
  );
  NOT _36_ (
    .A(valid),
    .Y(_11_)
  );
  NOR _37_ (
    .A(_11_),
    .B(_10_),
    .Y(_01_[0])
  );
  NOT _38_ (
    .A(data_in[1]),
    .Y(_12_)
  );
  NOR _39_ (
    .A(_12_),
    .B(_11_),
    .Y(_01_[1])
  );
  NOT _40_ (
    .A(data_in[2]),
    .Y(_13_)
  );
  NOR _41_ (
    .A(_13_),
    .B(_11_),
    .Y(_01_[2])
  );
  NOT _42_ (
    .A(data_in[3]),
    .Y(_14_)
  );
  NOR _43_ (
    .A(_14_),
    .B(_11_),
    .Y(_01_[3])
  );
  NOT _44_ (
    .A(data_in[4]),
    .Y(_15_)
  );
  NOR _45_ (
    .A(_15_),
    .B(_11_),
    .Y(_01_[4])
  );
  NOT _46_ (
    .A(data_in[5]),
    .Y(_16_)
  );
  NOR _47_ (
    .A(_16_),
    .B(_11_),
    .Y(_01_[5])
  );
  NOT _48_ (
    .A(data_in[6]),
    .Y(_17_)
  );
  NOR _49_ (
    .A(_17_),
    .B(_11_),
    .Y(_01_[6])
  );
  NOT _50_ (
    .A(data_in[7]),
    .Y(_18_)
  );
  NOR _51_ (
    .A(_18_),
    .B(_11_),
    .Y(_01_[7])
  );
  NOT _52_ (
    .A(data_ant[0]),
    .Y(_19_)
  );
  NOR _53_ (
    .A(_19_),
    .B(_03_),
    .Y(_00_[0])
  );
  DFF _54_ (
    .C(cclk),
    .D(data_in[1]),
    .Q(data_ant[1])
  );
  DFF _55_ (
    .C(cclk),
    .D(data_in[2]),
    .Q(data_ant[2])
  );
  DFF _56_ (
    .C(cclk),
    .D(data_in[3]),
    .Q(data_ant[3])
  );
  DFF _57_ (
    .C(cclk),
    .D(data_in[4]),
    .Q(data_ant[4])
  );
  DFF _58_ (
    .C(cclk),
    .D(data_in[5]),
    .Q(data_ant[5])
  );
  DFF _59_ (
    .C(cclk),
    .D(data_in[6]),
    .Q(data_ant[6])
  );
  DFF _60_ (
    .C(cclk),
    .D(data_in[7]),
    .Q(data_ant[7])
  );
  DFF _61_ (
    .C(cclk),
    .D(valid),
    .Q(valid_ant)
  );
  DFF _62_ (
    .C(bclk),
    .D(valid_ant),
    .Q(valid_out0)
  );
  DFF _63_ (
    .C(bclk),
    .D(valid),
    .Q(valid_out1)
  );
  DFF _64_ (
    .C(bclk),
    .D(_00_[0]),
    .Q(data_out0[0])
  );
  DFF _65_ (
    .C(bclk),
    .D(_00_[1]),
    .Q(data_out0[1])
  );
  DFF _66_ (
    .C(bclk),
    .D(_00_[2]),
    .Q(data_out0[2])
  );
  DFF _67_ (
    .C(bclk),
    .D(_00_[3]),
    .Q(data_out0[3])
  );
  DFF _68_ (
    .C(bclk),
    .D(_00_[4]),
    .Q(data_out0[4])
  );
  DFF _69_ (
    .C(bclk),
    .D(_00_[5]),
    .Q(data_out0[5])
  );
  DFF _70_ (
    .C(bclk),
    .D(_00_[6]),
    .Q(data_out0[6])
  );
  DFF _71_ (
    .C(bclk),
    .D(_00_[7]),
    .Q(data_out0[7])
  );
  DFF _72_ (
    .C(bclk),
    .D(_01_[0]),
    .Q(data_out1[0])
  );
  DFF _73_ (
    .C(bclk),
    .D(_01_[1]),
    .Q(data_out1[1])
  );
  DFF _74_ (
    .C(bclk),
    .D(_01_[2]),
    .Q(data_out1[2])
  );
  DFF _75_ (
    .C(bclk),
    .D(_01_[3]),
    .Q(data_out1[3])
  );
  DFF _76_ (
    .C(bclk),
    .D(_01_[4]),
    .Q(data_out1[4])
  );
  DFF _77_ (
    .C(bclk),
    .D(_01_[5]),
    .Q(data_out1[5])
  );
  DFF _78_ (
    .C(bclk),
    .D(_01_[6]),
    .Q(data_out1[6])
  );
  DFF _79_ (
    .C(bclk),
    .D(_01_[7]),
    .Q(data_out1[7])
  );
  DFF _80_ (
    .C(cclk),
    .D(data_in[0]),
    .Q(data_ant[0])
  );
endmodule
