/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "paralelo_serial_rx.v:1" *)
module paralelo_serial_rx(clk_32f, active, default_values, data_out);
  (* src = "paralelo_serial_rx.v:12" *)
  wire [7:0] _0_;
  wire _1_;
  (* src = "paralelo_serial_rx.v:3" *)
  input active;
  (* src = "paralelo_serial_rx.v:2" *)
  input clk_32f;
  (* src = "paralelo_serial_rx.v:5" *)
  output [7:0] data_out;
  (* src = "paralelo_serial_rx.v:4" *)
  input default_values;
  NOT _2_ (
    .A(default_values),
    .Y(_0_[5])
  );
  NOT _3_ (
    .A(active),
    .Y(_1_)
  );
  NOR _4_ (
    .A(_1_),
    .B(default_values),
    .Y(_0_[6])
  );
  NOR _5_ (
    .A(active),
    .B(default_values),
    .Y(_0_[7])
  );
  DFF _6_ (
    .C(clk_32f),
    .D(_0_[5]),
    .Q(data_out[2])
  );
  DFF _7_ (
    .C(clk_32f),
    .D(_0_[6]),
    .Q(data_out[6])
  );
  DFF _8_ (
    .C(clk_32f),
    .D(_0_[7]),
    .Q(data_out[7])
  );
  assign { data_out[5:3], data_out[1:0] } = { data_out[2], data_out[2], data_out[2], 2'b00 };
endmodule
