/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "paralelo_serial_phy_rx.v:1" *)
module paralelo_serial_phy_rx_estructural6(data_out, clk_4f, clk_32f, active);
  wire _0_;
  wire _1_;
  (* src = "paralelo_serial_phy_rx.v:5" *)
  input active;
  (* src = "paralelo_serial_phy_rx.v:4" *)
  input clk_32f;
  (* src = "paralelo_serial_phy_rx.v:3" *)
  input clk_4f;
  (* src = "paralelo_serial_phy_rx.v:2" *)
  output [7:0] data_out;
  NOT _2_ (
    .A(_0_),
    .Y(_1_)
  );
  assign data_out[6:0] = { active, 6'b111100 };
  assign _0_ = active;
  assign data_out[7] = _1_;
endmodule
