/* Generated by Yosys 0.9+4052 (git sha1 86a6ac76, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "8_to_1_bits.v:1.1-37.10" *)
module converter_bits(cclk, dclk, default_values, data_in, data_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  (* src = "8_to_1_bits.v:2.12-2.16" *)
  input cclk;
  (* src = "8_to_1_bits.v:12.12-12.15" *)
  wire [2:0] cnt;
  (* src = "8_to_1_bits.v:5.16-5.23" *)
  input [7:0] data_in;
  (* src = "8_to_1_bits.v:6.14-6.22" *)
  output data_out;
  (* src = "8_to_1_bits.v:3.12-3.16" *)
  input dclk;
  (* src = "8_to_1_bits.v:4.11-4.25" *)
  input default_values;
  NOT _37_ (
    .A(default_values),
    .Y(_04_)
  );
  NOT _38_ (
    .A(cnt[2]),
    .Y(_05_)
  );
  NOT _39_ (
    .A(cnt[1]),
    .Y(_06_)
  );
  NOT _40_ (
    .A(cnt[0]),
    .Y(_07_)
  );
  NOT _41_ (
    .A(data_in[4]),
    .Y(_08_)
  );
  NOR _42_ (
    .A(cnt[1]),
    .B(cnt[0]),
    .Y(_09_)
  );
  NAND _43_ (
    .A(cnt[1]),
    .B(cnt[0]),
    .Y(_10_)
  );
  NOR _44_ (
    .A(default_values),
    .B(_09_),
    .Y(_11_)
  );
  NAND _45_ (
    .A(_10_),
    .B(_11_),
    .Y(_02_)
  );
  NAND _46_ (
    .A(_04_),
    .B(cnt[0]),
    .Y(_01_)
  );
  NAND _47_ (
    .A(_05_),
    .B(data_in[3]),
    .Y(_12_)
  );
  NAND _48_ (
    .A(cnt[2]),
    .B(data_in[7]),
    .Y(_13_)
  );
  NAND _49_ (
    .A(_12_),
    .B(_13_),
    .Y(_14_)
  );
  NAND _50_ (
    .A(cnt[0]),
    .B(_14_),
    .Y(_15_)
  );
  NOR _51_ (
    .A(cnt[2]),
    .B(data_in[2]),
    .Y(_16_)
  );
  NOR _52_ (
    .A(_05_),
    .B(data_in[6]),
    .Y(_17_)
  );
  NOR _53_ (
    .A(_16_),
    .B(_17_),
    .Y(_18_)
  );
  NAND _54_ (
    .A(_07_),
    .B(_18_),
    .Y(_19_)
  );
  NAND _55_ (
    .A(_15_),
    .B(_19_),
    .Y(_20_)
  );
  NAND _56_ (
    .A(cnt[2]),
    .B(data_in[5]),
    .Y(_21_)
  );
  NAND _57_ (
    .A(_05_),
    .B(data_in[1]),
    .Y(_22_)
  );
  NAND _58_ (
    .A(_21_),
    .B(_22_),
    .Y(_23_)
  );
  NAND _59_ (
    .A(cnt[0]),
    .B(_23_),
    .Y(_24_)
  );
  NOR _60_ (
    .A(cnt[2]),
    .B(data_in[0]),
    .Y(_25_)
  );
  NAND _61_ (
    .A(cnt[2]),
    .B(_08_),
    .Y(_26_)
  );
  NAND _62_ (
    .A(_07_),
    .B(_26_),
    .Y(_27_)
  );
  NOR _63_ (
    .A(_25_),
    .B(_27_),
    .Y(_28_)
  );
  NOR _64_ (
    .A(_06_),
    .B(_20_),
    .Y(_29_)
  );
  NOR _65_ (
    .A(cnt[1]),
    .B(_28_),
    .Y(_30_)
  );
  NAND _66_ (
    .A(_24_),
    .B(_30_),
    .Y(_31_)
  );
  NAND _67_ (
    .A(_04_),
    .B(_31_),
    .Y(_32_)
  );
  NOR _68_ (
    .A(_29_),
    .B(_32_),
    .Y(_00_)
  );
  NOR _69_ (
    .A(cnt[2]),
    .B(_09_),
    .Y(_33_)
  );
  NOT _70_ (
    .A(_33_),
    .Y(_34_)
  );
  NAND _71_ (
    .A(cnt[2]),
    .B(_09_),
    .Y(_35_)
  );
  NAND _72_ (
    .A(_34_),
    .B(_35_),
    .Y(_36_)
  );
  NAND _73_ (
    .A(_04_),
    .B(_36_),
    .Y(_03_)
  );
  (* src = "8_to_1_bits.v:15.5-35.8" *)
  DFF _74_ (
    .C(dclk),
    .D(_00_),
    .Q(data_out)
  );
  (* src = "8_to_1_bits.v:15.5-35.8" *)
  DFF _75_ (
    .C(dclk),
    .D(_01_),
    .Q(cnt[0])
  );
  (* src = "8_to_1_bits.v:15.5-35.8" *)
  DFF _76_ (
    .C(dclk),
    .D(_02_),
    .Q(cnt[1])
  );
  (* src = "8_to_1_bits.v:15.5-35.8" *)
  DFF _77_ (
    .C(dclk),
    .D(_03_),
    .Q(cnt[2])
  );
endmodule
